parameters:
    locale: ru

jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: password, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        admin_secured_area:
            pattern:   ^/cards
            anonymous: ~
            provider: in_memory
            form_login:
                login_path: /cards/auth
                check_path: /cards/login_check
                username_parameter: authform[name]
                password_parameter: authform[password]
            logout:
                path:   /cards/logout
                target: /cards/auth

    access_control:
        - { path: ^/cards/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cards, roles: ROLE_ADMIN }

framework:
    secret: "denis1986"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v1
        cache:       ~
    default_locale:  "%locale%"
    trusted_proxies: ~
    fragments:       ~
    esi: {enabled: true}
    session:
        name: ~
        cookie_lifetime:    15552000

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: false
    cache: "%kernel.cache_dir%/twig"


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~

#Doctrine Configuration
doctrine:
    dbal:
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    ShopBonusCardBundle: ~
                    ShopShopBundle: ~
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

stof_doctrine_extensions:
        orm:
            default:
                tree: true
                softdeleteable: true
                timestampable: true


ornicar_apc:
      host: http://sftest.foto-planeta.net 
      web_dir: %kernel.root_dir%/../web

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: critical
