imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:
        only_exceptions: false
        only_master_requests: false      

web_profiler:
    toolbar: true
    intercept_redirects: false
    position: bottom

twig:
    debug: true
    exception_controller:  twig.controller.exception:showAction

doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_mysql
                host:     localhost
                dbname:   bonuscard
                user:     bonuscard-local
                password: 4ZK45N4CuexJRHNh
                charset:  UTF8
                logging:    %kernel.debug%
                profiling:  %kernel.debug%