shop_shop:
    resource: "@ShopShopBundle/Resources/config/routing.yml"
    prefix:   /

shop_bonus_card:
    resource: "@ShopBonusCardBundle/Resources/config/routing.yml"

admin_login_check:
    path: /cards/login_check

admin_logout:
    path: /cards/logout
