parameters:
#    shop_bonus_card.example.class: Shop\BonusCardBundle\Example

services:
#    shop_bonus_card.example:
#        class: %shop_bonus_card.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
