<?php

namespace Shop\BonusCardBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\QueryBuilder;

/**
 * CardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardsRepository extends EntityRepository
{
	public function getMaxNumber($series) {
		$querybuilder = $this->createQueryBuilder('c')
            ->select('MAX(c.number)')
            ->where('c.series = :series')
            ->setParameters([
            	':series' => $series,
            ]);
        return $querybuilder->getQuery()->getSingleResult();
	}

	public function getCardsSeries() {
		$querybuilder = $this->createQueryBuilder('c')
            ->select('DISTINCT(c.series)');
        return $querybuilder->getQuery()->getArrayResult();
	}
}